---
name: pulp-smash PR CI
on: pull_request

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dev requirements
        run: pip install -r dev_requirements.txt

      # Lint code
      - name: Run black
        run: |
          black --version
          black --check --diff .

      # check for any files unintentionally left out of MANIFEST.in
      - name: Check manifest
        run: check-manifest

      - run: pre-commit run -a -v
