---
name: pulp-smash PR CI
on: pull_request

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dev requirements
        run: pip install -r dev_requirements.txt

      - name: Run tests
        run: |
          python setup.py test
          git clean -dfx

      # run black separately from flake8 to get a diff
      - name: Run black
        run: |
          black --version
          black --check --diff .

      # Lint code.
      - name: Run flake8
        run: flake8 --config flake8.cfg

      # check for any files unintentionally left out of MANIFEST.in
      - name: Check manifest
        run: check-manifest

      - run: make all

      - run: pre-commit run -a -v

      - run: coveralls
